@startuml calendar-sinch-push

skinparam  {
    Maxmessagesize 200
}

skinparam sequence {
    participantPadding 30
    MessageAlign center
    roundcorner 10
}

skinparam Legend {
    BackgroundColor white
    FontColor black
    BorderThickness 0
    FontSize 14
}


autonumber
title Календарь

actor "user" as user order 10

box "Static" #yellow
    participant "calendar servddice" as cs order 20
    participant "cdddice" as css order 30
endbox
box "Rooms" #green
    participant "calendar integration service" as cis order 30
endbox

!$gc = "GET calendars"

user->cs: $gc
cs->cis: $gc
cis->css: $gc
css->ews: $gc

legend left
**Legend** fgfdgrfg
<#lightblue>|=Name |=Description |
|**Version**| 1.0|
|**Autor**| Burmistrov|
|**Data**| 10.04.24|
endlegend

@enduml